branches:
  except:
    - update

environment:
  global:
    PIPENV_NOSPIN: true
  matrix:
    - PYTHON_MAJOR: 2
      PYTHON_MINOR: 7
    - PYTHON_MAJOR: 3
      PYTHON_MINOR: 6

cache:
  - env

install:
  # Export build paths
  - copy C:\MinGW\bin\mingw32-make.exe C:\MinGW\bin\make.exe
  - set PATH=%PATH%;C:\MinGW\bin
  - make --version
  # Install system dependencies
  - make setup
  # Install project dependencies
  - make install

build: off

test_script:
  - make ci
