language: python
python:
- 3.3
- 3.4
- 2.7
env:
  global:
    - TRAVIS=true
  matrix:
    - TEST_RUNNER=nose
    - TEST_RUNNER=pytest
install:
- pip install coveralls scrutinizer-ocular
script: make ci
after_success:
- coveralls
- ocular
notifications:
  email:
    on_success: never
    on_failure: always
