environment:
  global:
    RANDOM_SEED: 0
    PIPENV_NOSPIN: true
  matrix:
    - PYTHON_MAJOR: {{cookiecutter.python_major_version}}
      PYTHON_MINOR: {{cookiecutter.python_minor_version}}

cache:
  - .venv -> .appveyor.yml

install:
  # Export build paths
  - copy C:\MinGW\bin\mingw32-make.exe C:\MinGW\bin\make.exe
  - set PATH=%PATH%;C:\MinGW\bin
  # Install system dependencies
  - pip install pipenv==3.6.1
  - make doctor
  # Install project dependencies
  - make install

build: off

test_script:
  - make check
  - make test
